name: Moban Sync

# Start ignoring YAMLLintBear
on: [push]
# Stop ignoring

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install Dependencies
        run: pip install moban~=0.5.0 gitfs2 pypifs
      - name: script
        run: |
          moban
          git diff --exit-code
